version: 0.2
env:
  variables:
    DOCKER_REGISTRY_USERNAME: "harshavarthini28"
    DOCKER_REGISTRY_PASSWORD: "Harsha#1234"
    DOCKER_REGISTRY_URL: "docker.io"
    
  # paramater_store:
  #   DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
  #   DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
  #   DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
      # - npm run lint
      # - npm run test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest"
  post_build:
    commands:
      - echo Packaging build artifacts...

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

