version: 0.2

phases:
  install:
    # runtime-versions:
    #   nodejs: 14
    commands:
      - echo Installing dependencies...
      - n 14.18.3
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
      - npm run lint
      - npm run test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging build artifacts...

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
